kvm-neu and vserver-neu changed from positional parameters to named parameters

diff --git a/usr/bin/kvm-neu b/usr/bin/kvm-neu
--- a/usr/bin/kvm-neu
+++ b/usr/bin/kvm-neu
@@ -1,16 +1,56 @@
 #!/bin/bash
 
 [ -e /etc/cluster-tools-lihas.conf ] && . /etc/cluster-tools-lihas.conf
+CRMONLY=0
+KVMNAME=""
+SIZE=""
+DRBD=""
 
-if [ ga$2 == ga ]; then
-  echo "usage: $0 KVMNAME SIZE [DRBDNUM]" >&2
-  echo "  z.B. $0 test01 30G" >&2
-  echo "  z.B. $0 test01 30G 3" >&2
+print_help() {
+	echo "Usage: $0 --kvmname=KVMNAME --size=SIZE --drbd=DRBDNUM [--print-crm-only]" >&2
+	echo "--kvmname: Name of KVM" >&2
+	echo "--size:    virtual disk size, e.g. 10G" >&2
+	echo "--drbd:    drbd device number to use" >&2
+	echo "--print-crm-only:    just print the resulting crm resources" >&2
+}
+error() {
+  print_help
+  echo "$*"
   exit 1
+}
+TEMP=`getopt -o h --long help,kvmname:,size:,drbd:,print-crm-only -- "$@"`
+if [ $? != 0 ] ; then print_help >&2 ; exit 1 ; fi
+eval set -- "$TEMP"
+while true ; do
+	case "$1" in
+		--kvmname) KVMNAME=$2; shift 2;;
+		--size) SIZE=$2; shift 2;;
+		--drbd) DRBD=$2; shift 2;;
+		--print-crm-only) CRMONLY=1; shift 1;;
+		--help|-h) print_help;;
+		--) shift ; break ;;
+		*) echo "Unknown parameter $1i, try -h" ; exit 1 ;;
+	esac
+done
+
+if [ "x$KVMNAME" == "x" ]; then
+	echo "Missing --kvmname" >&2
+	print_help
+	exit 1
+fi
+if [ "x$SIZE" == "x" ]; then
+	echo "Missing --size" >&2
+	print_help
+	exit 1
 fi
 
-KVMNAME=$1
-SIZE=$2
+#if [ ga$2 == ga ]; then
+#  echo "usage: $0 KVMNAME SIZE [DRBDNUM]" >&2
+#  echo "  z.B. $0 test01 30G" >&2
+#  echo "  z.B. $0 test01 30G 3" >&2
+#  exit 1
+#fi
+
 VIRSHINSTANCES="qemu:///system qemu+ssh://$HOST2/system"
 . $LIHASSOURCEDIR/usr/lib/cluster-tools-lihas/drbd-functions.sh
 DRBDVERSION=$(drbdversion)
@@ -32,20 +72,19 @@ if !([ -e $(which rsync) ]) ; then echo "Please Install rsync"; exit 1; fi
 if !([ -e $(which mktemp) ]) ; then echo "Please Install mktemp"; exit 1; fi
 if !([ -e $(which virsh) ]) ; then echo "Please Install libvirt-bin"; exit 1; fi
 
-if [ ga$3 == ga ]; then
+if [ "ga$DRBD" == "ga" ]; then
   DRBD=$(drbdnextfree)
-else
-  DRBD=$3
 fi
 
 DRBDPORT=$(printf "%02i" $DRBD)
 
 DUMMY=10
 
-lvcreate -L$SIZE -n kvm_$KVMNAME $VG1
-ssh $HOST2 lvcreate -L$SIZE -n kvm_$KVMNAME $VG2
+if [ $CRMONLY -eq 0 ]; then
+	lvcreate -L$SIZE -n kvm_$KVMNAME $VG1
+	ssh $HOST2 lvcreate -L$SIZE -n kvm_$KVMNAME $VG2
 
-cat <<-EOF > /etc/drbd.d/kvm_$KVMNAME.res
+	cat <<-EOF > /etc/drbd.d/kvm_$KVMNAME.res
 resource kvm_$KVMNAME {  
         protocol        C;
         syncer {
@@ -75,15 +114,15 @@ resource kvm_$KVMNAME {
 }
 EOF
 
-rsync -rlHpogDtSvx /etc/drbd.d $HOST2:/etc/
-yes yes | drbdadm create-md kvm_$KVMNAME
-drbdadm up kvm_$KVMNAME
-ssh $HOST2 "(yes yes | drbdadm create-md kvm_$KVMNAME && drbdadm up kvm_$KVMNAME)"
+	rsync -rlHpogDtSvx /etc/drbd.d $HOST2:/etc/
+	yes yes | drbdadm create-md kvm_$KVMNAME
+	drbdadm up kvm_$KVMNAME
+	ssh $HOST2 "(yes yes | drbdadm create-md kvm_$KVMNAME && drbdadm up kvm_$KVMNAME)"
 
-drbdprimaryforce $DRBDVERSION kvm_$KVMNAME
-parted /dev/drbd$DRBD mklabel msdos
-
-cat <<EOF | crm configure
+	drbdprimaryforce $DRBDVERSION kvm_$KVMNAME
+	parted /dev/drbd$DRBD mklabel msdos
+fi
+cat <<EOF | if [ $CRMONLY -eq 0 ]; then crm configure; else cat; fi
 primitive p_$KVMNAME ocf:linbit:drbd \
         params drbd_resource="kvm_$KVMNAME" \
         op start interval="0" timeout="240" \
@@ -98,20 +137,21 @@ ms ms_$KVMNAME p_$KVMNAME \
 commit
 EOF
 
-while ! drbd-overview | sed 's/:/ /g' | awk '$2 ~ /^kvm_'$KVMNAME'(\/.*|)$/' | grep -q Primary/Primary; do
-  cat /proc/drbd
-  sleep 5
-done
+if [ $CRMONLY -eq 0 ]; then
+	while ! drbd-overview | sed 's/:/ /g' | awk '$2 ~ /^kvm_'$KVMNAME'(\/.*|)$/' | grep -q Primary/Primary; do
+	  cat /proc/drbd
+	  sleep 5
+	done
 
-virsh pool-create-as --name $KVMNAME --type disk --source-path dev --source-dev /dev/drbd$DRBD --target /dev/
-virsh pool-dumpxml $KVMNAME > /etc/libvirt/storage/$KVMNAME.xml
-ln -s /etc/libvirt/storage/$KVMNAME.xml /etc/libvirt/storage/autostart/$KVMNAME.xml
-ssh $HOST2 /etc/init.d/libvirt-bin stop
-rsync -rlHpogDtSvx --numeric-ids /etc/libvirt $HOST2:/etc/
-ssh $HOST2 /etc/init.d/libvirt-bin start
-/etc/init.d/libvirt-bin restart
+	virsh pool-create-as --name $KVMNAME --type disk --source-path dev --source-dev /dev/drbd$DRBD --target /dev/
+	virsh pool-dumpxml $KVMNAME > /etc/libvirt/storage/$KVMNAME.xml
+	ln -s /etc/libvirt/storage/$KVMNAME.xml /etc/libvirt/storage/autostart/$KVMNAME.xml
+	ssh $HOST2 /etc/init.d/libvirt-bin stop
+	rsync -rlHpogDtSvx --numeric-ids /etc/libvirt $HOST2:/etc/
+	ssh $HOST2 /etc/init.d/libvirt-bin start
+	/etc/init.d/libvirt-bin restart
 
-DOMFILE=`mktemp`
+	DOMFILE=`mktemp`
 cat <<-EOF >$DOMFILE
 <domain type='kvm' id='3'>
   <name>$KVMNAME</name>
@@ -164,12 +204,12 @@ cat <<-EOF >$DOMFILE
 </domain>
 EOF
 
-for virshinstance in $VIRSHINSTANCES; do
-  virsh -c $virshinstance define $DOMFILE
-done
-rm $DOMFILE
-
-cat <<EOF | crm configure
+	for virshinstance in $VIRSHINSTANCES; do
+	  virsh -c $virshinstance define $DOMFILE
+	done
+	rm $DOMFILE
+fi
+cat <<EOF | if [ $CRMONLY -eq 0 ]; then crm configure; else cat; fi
 primitive res_VirtualDomain_kvm_$KVMNAME ocf:heartbeat:VirtualDomain \
         params config="/etc/libvirt/qemu/$KVMNAME.xml" \
         op start interval="0" timeout="90" \
@@ -185,4 +225,4 @@ commit
 EOF
 
 echo "Dinge tun, z.B. Bootmedium auswaehlen"
-
+# vim: ts=2 sw=2 sts=2 sr noet
diff --git a/usr/bin/vserver-neu b/usr/bin/vserver-neu
--- a/usr/bin/vserver-neu
+++ b/usr/bin/vserver-neu
@@ -1,26 +1,80 @@
 #!/bin/bash
 
 [ -e /etc/cluster-tools-lihas.conf ] && . /etc/cluster-tools-lihas.conf
+VSNAME=""
+IP=""
+SIZE=""
+CONTEXT=""
+DRBD=""
+CRMONLY=0
 
-if [ ga$4 == ga ]; then
-  echo "usage: $0 VSNAME IP SIZE CONTEXT [DRBDNUM]" >&2
-  echo "usage: $0 test01 10.0.0.115 10G 115" >&2
-  echo "usage: $0 test01 10.0.0.115 10G 115 3" >&2
+print_help() {
+  echo "Usage: $0 --name=VSNAME --ip=IP --size=SIZE --context=CTX --drbd=DRBDNUM [--print-crm-only]" >&2
+  echo "--name:    Name of VServer" >&2
+  echo "--ip:      IP of VServer" >&2
+  echo "--size:    virtual disk size, e.g. 10G" >&2
+  echo "--context: VServer context id" >&2
+  echo "--drbd:    drbd device number to use" >&2
+  echo "--print-crm-only:    just print the resulting crm resources" >&2
+}
+error() {
+  print_help
+  echo "$*"
+  exit 1
+}
+TEMP=`getopt -o h --long help,name:,ip:,size:,context:,drbd:,print-crm-only -- "$@"`
+if [ $? != 0 ] ; then print_help >&2 ; exit 1 ; fi
+eval set -- "$TEMP"
+while true ; do
+  case "$1" in
+    --name)    VSNAME=$2; shift 2;;
+    --ip)      IP=$2; shift 2;;
+    --size)    SIZE=$2; shift 2;;
+    --context) CONTEXT=$2; shift 2;;
+    --drbd)    DRBD=$2; shift 2;;
+    --print-crm-only) CRMONLY=1; shift 1;;
+    --help|-h) print_help;;
+    --) shift ; break ;;
+    *) echo "Unknown parameter $1, try -h" ; exit 1 ;;
+  esac
+done
+#if [ ga$4 == ga ]; then
+#  echo "usage: $0 VSNAME IP SIZE CONTEXT [DRBDNUM]" >&2
+#  echo "usage: $0 test01 10.0.0.115 10G 115" >&2
+#  echo "usage: $0 test01 10.0.0.115 10G 115 3" >&2
+#  exit 1
+#fi
+
+if [ "x$VSNAME" == "x" ]; then
+  echo "Missing --name" >&2
+  print_help
+  exit 1
+fi
+if [ "x$IP" == "x" ]; then
+  echo "Missing --ip" >&2
+  print_help
+  exit 1
+fi
+if [ "x$SIZE" == "x" ]; then
+  echo "Missing --size" >&2
+  print_help
+  exit 1
+fi
+if [ "x$CONTEXT" == "x" ]; then
+  echo "Missing --context" >&2
+  print_help
   exit 1
 fi
 
-VSNAME=$1
-IP=$2
-SIZE=$3
-CONTEXT=$4
-
 # IF Abfragen nach dem installierten Software, die benoetigt wird
 if [ ! -e /usr/bin/which    ] ; then echo "which ist nicht installiert!!!"; exit 1; fi
-if ! which crm      >/dev/null 2>&1; then echo "Please Install crm"; exit 1; fi
-if ! which drbdadm  >/dev/null 2>&1; then echo "Please Install drbd"; exit 1; fi
+if [ $CRMONLY -eq 0 ]; then
+	if ! which crm      >/dev/null 2>&1; then echo "Please Install crm"; exit 1; fi
+	if ! which drbdadm  >/dev/null 2>&1; then echo "Please Install drbd"; exit 1; fi
+	if ! which lvcreate >/dev/null 2>&1; then echo "Please Install lvm2"; exit 1; fi
+fi
 if ! which awk      >/dev/null 2>&1; then echo "Please Install awk"; exit 1; fi
 if ! which ssh      >/dev/null 2>&1; then echo "Please Install openssh"; exit 1; fi
-if ! which lvcreate >/dev/null 2>&1; then echo "Please Install lvm2"; exit 1; fi
 if ! which rsync    >/dev/null 2>&1; then echo "Please Install rsync"; exit 1; fi
 if ! which mktemp   >/dev/null 2>&1; then echo "Please Install mktemp"; exit 1; fi
 if ! which ipcalc   >/dev/null 2>&1; then echo "Please Install ipcalc"; exit 1; fi
@@ -29,21 +83,20 @@ BROADCAST=$(ipcalc $IP/$IF_LAN_NM | awk '$2 ~ /^Broadcast:$/ {print $2}')
 . $LIHASSOURCEDIR/usr/lib/cluster-tools-lihas/drbd-functions.sh
 DRBDVERSION=$(drbdversion)
 
-if [ ga$5 == ga ]; then
+if [ ga$DRBD == ga ]; then
   # Naechstes freies DRBD
   DRBD=$(drbdnextfree)
-else
-  DRBD=$5
 fi
 
 DRBDPORT=$(printf "%02i" $DRBD)
 
 DUMMY=10
 
-lvcreate -L$SIZE -n vs_$VSNAME $VG1
-ssh $HOST2 lvcreate -L$SIZE -n vs_$VSNAME $VG2
+if [ $CRMONLY -eq 0 ]; then
+	lvcreate -L$SIZE -n vs_$VSNAME $VG1
+	ssh $HOST2 lvcreate -L$SIZE -n vs_$VSNAME $VG2
 
-cat <<-EOF > /etc/drbd.d/vs_$VSNAME.res
+	cat <<-EOF > /etc/drbd.d/vs_$VSNAME.res
 resource vs_$VSNAME {  
         protocol        C;
         syncer {
@@ -64,27 +117,28 @@ resource vs_$VSNAME {
 }
 EOF
 
-rsync -rlHpogDtSvx /etc/drbd.d $HOST2:/etc/
-yes yes | drbdadm create-md vs_$VSNAME
-drbdadm up vs_$VSNAME
-ssh $HOST2 "(yes yes | drbdadm create-md vs_$VSNAME && drbdadm up vs_$VSNAME)"
+	rsync -rlHpogDtSvx /etc/drbd.d $HOST2:/etc/
+	yes yes | drbdadm create-md vs_$VSNAME
+	drbdadm up vs_$VSNAME
+	ssh $HOST2 "(yes yes | drbdadm create-md vs_$VSNAME && drbdadm up vs_$VSNAME)"
 
-drbdprimaryforce $DRBDVERSION vs_$VSNAME
+	drbdprimaryforce $DRBDVERSION vs_$VSNAME
 
-mkfs.ext4 -L vs_$VSNAME /dev/drbd$DRBD
-mount /dev/drbd$DRBD /mnt
-vserver $VSNAME build --context $CONTEXT --interface $IF_LAN:$IP/$IF_LAN_NM --hostname $VSNAME -m debootstrap -- -d $DEBIANDIST
-cat $VSERVER_TEMPLATE/etc/apt/sources.list > $VSERVER_BASE/$VSNAME/etc/apt/sources.list
-sed -i '/tmpfs/d' /etc/vservers/$VSNAME/fstab
-touch /etc/vservers/$VSNAME/interfaces/0/nodev
-mv $VSERVER_BASE/$VSNAME/* /mnt/
-umount /mnt 
+	mkfs.ext4 -L vs_$VSNAME /dev/drbd$DRBD
+	mount /dev/drbd$DRBD /mnt
+	vserver $VSNAME build --context $CONTEXT --interface $IF_LAN:$IP/$IF_LAN_NM --hostname $VSNAME -m debootstrap -- -d $DEBIANDIST
+	cat $VSERVER_TEMPLATE/etc/apt/sources.list > $VSERVER_BASE/$VSNAME/etc/apt/sources.list
+	sed -i '/tmpfs/d' /etc/vservers/$VSNAME/fstab
+	touch /etc/vservers/$VSNAME/interfaces/0/nodev
+	mv $VSERVER_BASE/$VSNAME/* /mnt/
+	umount /mnt 
 
-ssh $HOST2 mkdir $VSERVER_BASE/$VSNAME
+	ssh $HOST2 mkdir $VSERVER_BASE/$VSNAME
 
-rsync -rlHpogDtSvx /etc/vservers $HOST2:/etc/
+	rsync -rlHpogDtSvx /etc/vservers $HOST2:/etc/
+fi
 
-cat <<EOF | crm configure
+cat <<EOF | if [ $CRMONLY -eq 0 ]; then crm configure; else cat; fi
 primitive res_drbd_drbd$DRBD_$VSNAME ocf:linbit:drbd \
         params drbd_resource="vs_$VSNAME" \
         operations \$id="res_drbd_drbd$VSNAME-operations" \
@@ -121,10 +175,13 @@ order ord_ms_$VSNAME-grp_$VSNAME inf: ms_$VSNAME:promote grp_$VSNAME:start
 commit
 EOF
 
-if [ "x$VSHOOKPOST" != "x" ]; then
-  export VSNAME
-  export IP
-  export SIZE
-  export CONTEXT
-  $VSHOOKPOST
+if [ $CRMONLY -eq 0 ]; then
+	if [ "x$VSHOOKPOST" != "x" ]; then
+	  export VSNAME
+	  export IP
+	  export SIZE
+	  export CONTEXT
+	  $VSHOOKPOST
+	fi
 fi
+# vim: ts=2 sw=2 sts=2 sr noet
