lxc-neu: --vampire-stage

diff --git a/usr/bin/lxc-neu b/usr/bin/lxc-neu
--- a/usr/bin/lxc-neu
+++ b/usr/bin/lxc-neu
@@ -17,7 +17,8 @@ print_help() {
   echo "--interface:    host network interface" >&2
   echo "--print-crm-only:    just print the resulting crm resources" >&2
   echo "--force-dataloss:    use lv despite it already exists" >&2
-  echo "--vampire: rip filesystem from VS_HOST:/VS_PATH via rsync" >&2
+  echo "--vampire:           rip filesystem from VS_HOST:/VS_PATH via rsync" >&2
+  echo "--vampire-stage:     stage: 1: create lxc, 2: rsync, 3: change uids/gids" >&2
 }
 error() {
   print_help
@@ -37,6 +38,7 @@ DIST=debian
 RELEASE=stretch
 IF_LAN=br0
 VAMPIRE=""
+VAMPIRE_STAGE=0
 MAC_RAND=$(
   perl -le 'sysread(STDIN,$a,5); (@a)=unpack("CCCCC",$a); printf "%02x:%02x:%02x:%02x:%02x\n",@a' < /dev/random
 )
@@ -45,7 +47,7 @@ if [ $CONTAINER_SUBUID -lt $CONTAINER_SUBGID ]; then
   CONTAINER_SUBUID=$CONTAINER_SUBGID
 fi
 [ -e /etc/cluster-tools-lihas.conf ] && . /etc/cluster-tools-lihas.conf
-TEMP=`getopt -o h --long help,single,unpriv,name:,size:,drbd:,ip:,netmask:,gateway:,interface:,dist:,release:,force-dataloss,print-crm-only,mac,vampire: -- "$@"`
+TEMP=`getopt -o h --long help,single,unpriv,name:,size:,drbd:,ip:,netmask:,gateway:,interface:,dist:,release:,force-dataloss,print-crm-only,mac,vampire:,vampire-stage: -- "$@"`
 if [ $? != 0 ] ; then print_help >&2 ; exit 1 ; fi
 eval set -- "$TEMP"
 while true ; do
@@ -65,6 +67,7 @@ while true ; do
     --print-crm-only) CRMONLY=1; shift 1;;
     --force-dataloss) FORCE_DATALOSS=1; shift 1;;
     --vampire) VAMPIRE=$2; shift 2;;
+    --vampire-stage) VAMPIRE_STAGE=$2; shift 2;;
     --help|-h) print_help; shift 1; exit 1;;
     --) shift ; break ;;
     *) echo "Unknown parameter $1, try -h" ; exit 1 ;;
@@ -85,6 +88,13 @@ if [ $UNPRIV -eq 1 ] && [ $SINGLE -eq 0 ]; then
   echo "unprivileged containers are not yet supported in HA environments" >&2
   print_help
   exit 1
+fi
+if [ x"$VAMPIRE" != x ]; then
+  if [ x"$VAMPIRE_STAGE" != x1 ] && [ x"$VAMPIRE_STAGE" != x2 ] && [ x"$VAMPIRE_STAGE" != x3 ]; then
+    echo "--vampire-stage [1|2|3] needed" >&2
+    print_help
+    exit 1
+  fi
 fi
 
 # IF Abfragen nach dem installierten Software, die benoetigt wird
@@ -136,18 +146,27 @@ if [ $CRMONLY -eq 0 ]; then
   if [ $FORCE_DATALOSS -ne 1 ]; then
     if [ "x$SINGLE" == "x0" ]; then
       if [ -e /etc/drbd.d/lxc_$VSNAME.res ]; then
-        echo "WARNING: /etc/drbd.d/lxc_$VSNAME.res already exists, use --force-data-loss to continue anyway" >&2
-        exit 1
+        if [ x"$VAMPIRE" != x ] && [ $VAMPIRE_STAGE -eq 1 ] || [ x"$VAMPIRE" == x ]; then
+          echo "WARNING: /etc/drbd.d/lxc_$VSNAME.res already exists, use --force-data-loss to continue anyway" >&2
+          exit 1
+        fi
       fi
     fi
     if [ $(lvs | awk '$2 == "'$VG1'" && $1 == "'lxc_$VSNAME'" {print}' | wc -l ) -ne 0 ]; then
-      echo "WARNING: /dev/$VG1/lxc_$VSNAME already exists, use --force-data-loss to continue anyway" >&2
+      if [ x"$VAMPIRE" != x ] && [ $VAMPIRE_STAGE -eq 1 ] || [ x"$VAMPIRE" == x ]; then
+        echo "WARNING: /dev/$VG1/lxc_$VSNAME already exists, use --force-data-loss to continue anyway" >&2
+        exit 1
+      fi
+    elif [ x"$VAMPIRE" != x ] && [ $VAMPIRE_STAGE -gt 1 ]; then
+      echo "ERROR: --vampire-stage 1 not successfully done, yet" >&2
       exit 1
     fi
     if [ "x$SINGLE" == "x0" ]; then
       if [ $(ssh $HOST2 lvs | awk '$2 == "'$VG2'" && $1 == "'lxc_$VSNAME'" {print}' | wc -l ) -ne 0 ]; then
-        echo "WARNING: $HOST2:/dev/$VG2/lxc_$VSNAME already exists, use --force-data-loss to continue anyway" >&2
-        exit 1
+        if [ x"$VAMPIRE" != x ] && [ $VAMPIRE_STAGE -eq 1 ] || [ x"$VAMPIRE" == x ]; then
+          echo "WARNING: $HOST2:/dev/$VG2/lxc_$VSNAME already exists, use --force-data-loss to continue anyway" >&2
+          exit 1
+        fi
       fi
     fi
   fi
@@ -172,31 +191,34 @@ if [ $CRMONLY -eq 0 ]; then
 	MAC:       $CONTAINER_MACADDR
 	HOST-net:  $IF_LAN
 	Netz:      $CONTAINER_IP/$IF_LAN_NM
-	Gateway    $CONTAINER_GATEWAY
+	Gateway:   $CONTAINER_GATEWAY
+	Vampire:   $VAMPIRE
+	Vampire Stage:   $VAMPIRE_STAGE
 	***********************
 	* CLUSTER is untested *
 	***********************
 	continue: return, ctrl-c to abort
 EOF
   read a
-  lvcreate -L$SIZE -n lxc_${VSNAME//-/_} $VG1
-  if [ x$UNPRIV == x1 ]; then
-    touch /etc/subuid
-    vo -o /etc/subuid
-    cat <<-EOF >> /etc/subuid
+  if [ x"$VAMPIRE" != x ] && [ $VAMPIRE_STAGE -eq 1 ] || [ x"$VAMPIRE" == x ]; then
+    lvcreate -L$SIZE -n lxc_${VSNAME//-/_} $VG1
+    if [ x$UNPRIV == x1 ]; then
+      touch /etc/subuid
+      vo -o /etc/subuid
+      cat <<-EOF >> /etc/subuid
 	root:$CONTAINER_SUBUID:99999
 EOF
-    vo -i /etc/subuid
-    touch /etc/subgid
-    vo -o /etc/subgid
-    cat <<-EOF >> /etc/subgid
+      vo -i /etc/subuid
+      touch /etc/subgid
+      vo -o /etc/subgid
+      cat <<-EOF >> /etc/subgid
 	root:$CONTAINER_SUBUID:99999
 EOF
-    vo -i /etc/subgid
-  fi
-  if [ "x$SINGLE" == "x0" ]; then
-    ssh $HOST2 lvcreate -L$SIZE -n lxc_${VSNAME//-/_} $VG2
-    cat <<-EOF > /etc/drbd.d/lxc_$VSNAME.res
+      vo -i /etc/subgid
+    fi
+    if [ "x$SINGLE" == "x0" ]; then
+      ssh $HOST2 lvcreate -L$SIZE -n lxc_${VSNAME//-/_} $VG2
+      cat <<-EOF > /etc/drbd.d/lxc_$VSNAME.res
 resource lxc_$VSNAME {  
         protocol        C;
         syncer {
@@ -217,35 +239,41 @@ resource lxc_$VSNAME {
 }
 EOF
   
-    rsync -rlHpogDtSvx --numeric-ids /etc/drbd.d $HOST2:/etc/
-    yes yes | drbdadm create-md lxc_$VSNAME
-    drbdadm up lxc_$VSNAME
-    ssh $HOST2 "(yes yes | drbdadm create-md lxc_$VSNAME && drbdadm up lxc_$VSNAME)"
+      rsync -rlHpogDtSvx --numeric-ids /etc/drbd.d $HOST2:/etc/
+      yes yes | drbdadm create-md lxc_$VSNAME
+      drbdadm up lxc_$VSNAME
+      ssh $HOST2 "(yes yes | drbdadm create-md lxc_$VSNAME && drbdadm up lxc_$VSNAME)"
     
-    drbdprimaryforce $DRBDVERSION lxc_$VSNAME
+      drbdprimaryforce $DRBDVERSION lxc_$VSNAME
     
-    mkfs.ext4 -L lxc_$VSNAME /dev/drbd$DRBD
-    mkdir /var/lib/lxc/$VSNAME
-    mount /dev/drbd$DRBD /var/lib/lxc/$VSNAME
-    ssh $HOST2 mkdir /var/lib/lxc/$VSNAME
-  else
-    mkfs.ext4 -L lxc_$VSNAME /dev/$VG1/lxc_$VSNAME
-    mkdir -p /etc/RCS
-    vo -o /etc/fstab
-    cat <<-EOF >> /etc/fstab
+      mkfs.ext4 -L lxc_$VSNAME /dev/drbd$DRBD
+      mkdir /var/lib/lxc/$VSNAME
+      mount /dev/drbd$DRBD /var/lib/lxc/$VSNAME
+      ssh $HOST2 mkdir /var/lib/lxc/$VSNAME
+    else
+      mkfs.ext4 -L lxc_$VSNAME /dev/$VG1/lxc_$VSNAME
+      mkdir -p /etc/RCS
+      vo -o /etc/fstab
+      cat <<-EOF >> /etc/fstab
 	/dev/$VG1/lxc_${VSNAME//-/_} /var/lib/lxc/$VSNAME ext4 barrier=0,noatime 0 2
 EOF
-    vo -i /etc/fstab
-    mkdir /var/lib/lxc/$VSNAME
-    mount /var/lib/lxc/$VSNAME
+      vo -i /etc/fstab
+      mkdir /var/lib/lxc/$VSNAME
+      mount /var/lib/lxc/$VSNAME
+    fi
   fi
   if [ x"$VAMPIRE" == x ]; then
     lxc-create -n $VSNAME -t $DIST -- -r $RELEASE $CONTAINER_PACKAGES_ARG
   else
-    lxc-create -n $VSNAME -t none
-    rsync -rlHpogDtSvXA --numeric-ids $VAMPIRE/* /var/lib/lxc/$VSNAME/rootfs/
-    if [ ! -d /var/lib/lxc/$VSNAME/rootfs/run ]; then
-      mkdir /var/lib/lxc/$VSNAME/rootfs/run
+    if [ $VAMPIRE_STAGE -eq 1 ]; then
+      lxc-create -n $VSNAME -t none
+    fi
+    if [ $VAMPIRE_STAGE -eq 2 ]; then
+      rsync -rlHpogDtSvXA --numeric-ids $VAMPIRE/* /var/lib/lxc/$VSNAME/rootfs/
+      if [ ! -d /var/lib/lxc/$VSNAME/rootfs/run ]; then
+        rm /var/lib/lxc/$VSNAME/rootfs/run
+        mkdir /var/lib/lxc/$VSNAME/rootfs/run
+      fi
     fi
   fi
   if [ ! -f /var/lib/lxc/default.conf ] ; then
@@ -292,10 +320,11 @@ EOF
     vo -i /var/lib/lxc/default.conf
   fi
   # Die Container-spezifische Config
-  touch /var/lib/lxc/$VSNAME/config
-  mkdir -p /var/lib/lxc/$VSNAME/RCS
-  vo -o /var/lib/lxc/$VSNAME/config
-  cat << EOF > /var/lib/lxc/$VSNAME/config
+  if [ x"$VAMPIRE" != x ] && [ $VAMPIRE_STAGE -eq 1 ] || [ x"$VAMPIRE" == x ]; then
+    touch /var/lib/lxc/$VSNAME/config
+    mkdir -p /var/lib/lxc/$VSNAME/RCS
+    vo -o /var/lib/lxc/$VSNAME/config
+    cat << EOF > /var/lib/lxc/$VSNAME/config
 	lxc.include = /var/lib/lxc/default.conf
 	
 	lxc.rootfs = /var/lib/lxc/$VSNAME/rootfs
@@ -310,17 +339,19 @@ EOF
 	
 EOF
 	
-  if [ x$UNPRIV == x1 ]; then
-  cat << EOF >> /var/lib/lxc/$VSNAME/config
+    if [ x$UNPRIV == x1 ]; then
+    cat << EOF >> /var/lib/lxc/$VSNAME/config
 	lxc.id_map = u 0 $CONTAINER_SUBUID 99999
 	lxc.id_map = g 0 $CONTAINER_SUBUID 99999
 EOF
+    fi
+    vo -i /var/lib/lxc/$VSNAME/config
   fi
-  vo -i /var/lib/lxc/$VSNAME/config
-
-  # permissions auf das subuid-Setup anpassen:
-  if [ "x$UNPRIV" == x1 ]; then
-    ownrecalc -U "*" -G "*" -u +$CONTAINER_SUBUID -g +$CONTAINER_SUBUID -d /var/lib/lxc/$VSNAME/rootfs
+  if [ x"$VAMPIRE" != x ] && [ $VAMPIRE_STAGE -eq 3 ] || [ x"$VAMPIRE" == x ]; then
+    # permissions auf das subuid-Setup anpassen:
+    if [ "x$UNPRIV" == x1 ]; then
+      ownrecalc -U "*" -G "*" -u +$CONTAINER_SUBUID -g +$CONTAINER_SUBUID -d /var/lib/lxc/$VSNAME/rootfs
+    fi
   fi
 fi
 LXCHA=ocf:lihas:lxc
@@ -328,8 +359,9 @@ LXCHA=ocf:lihas:lxc
 #if [ -e /usr/lib/ocf/resource.d/heartbeat/lxc ]; then
 #  LXCHA=ocf:heartbeat:lxc
 #fi
-if [ "x$SINGLE" == "x0" ]; then
-  cat <<-EOF | if [ $CRMONLY -eq 0 ]; then crm configure; else cat; fi
+if [ x"$VAMPIRE" != x ] && [ $VAMPIRE_STAGE -eq 1 ] || [ x"$VAMPIRE" == x ]; then
+  if [ "x$SINGLE" == "x0" ]; then
+    cat <<-EOF | if [ $CRMONLY -eq 0 ]; then crm configure; else cat; fi
 	primitive res_drbd_$DRBD_$VSNAME ocf:linbit:drbd \
 	        params drbd_resource="lxc_$VSNAME" stop_outdates_secondary=true unfence_extra_args=false \
 	        operations \$id="res_drbd_$VSNAME-operations" \
@@ -360,12 +392,13 @@ if [ "x$SINGLE" == "x0" ]; then
 	order ord_ms_$VSNAME-grp_$VSNAME inf: ms_$VSNAME:promote grp_$VSNAME:start
 	commit
 EOF
-fi
+  fi
 
-if [ "x$VSHOOKPOST" != "x" ]; then
-  export VSNAME
-  export IP
-  export SIZE
-  export CONTEXT
-  $VSHOOKPOST
+  if [ "x$VSHOOKPOST" != "x" ]; then
+    export VSNAME
+    export IP
+    export SIZE
+    export CONTEXT
+    $VSHOOKPOST
+  fi
 fi
